###
POST http://localhost:9000/inventario/insumos HTTP/1.1
Content-Type: application/json

{
  "categoria_insumo": "material-quirurgico",
  "descripcion_insumo": "Material quirurgico de un solo uso.",
  "estado_item": "Activo",
  "fecha_vencimiento": "2030-01-24",
  "id_insumo": "4444",
  "nombre_insumo": "Guantes quirurgicos x2",
  "stock_disponible": "21"
}